name: Publish to JSR

on:
  push:
    branches: ["steno", "main"]
  workflow_dispatch:

jobs:
  publish-jsr:
    if: contains(github.event.comment.body, 'Publish this Release') || startsWith(github.event.head_commit.message, 'release:') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task check
      - run: deno publish
